// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8T6W099hSsFf-WTiQC6-rW4VzklR6qNg',
    appId: '1:961049919020:web:31c08a47eebb361e4fdb89',
    messagingSenderId: '961049919020',
    projectId: 'wasteexpert-64848',
    authDomain: 'wasteexpert-64848.firebaseapp.com',
    storageBucket: 'wasteexpert-64848.appspot.com',
    measurementId: 'G-3LMJFKP02E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCBc_l9L6HSFqDFA1M-eNhh_8bWYQ52A',
    appId: '1:961049919020:android:7838c82b646c48a04fdb89',
    messagingSenderId: '961049919020',
    projectId: 'wasteexpert-64848',
    storageBucket: 'wasteexpert-64848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWEroHjEi2K9YLct7aSRit4ED36C8O9s',
    appId: '1:961049919020:ios:ff1ebb4b61331fd14fdb89',
    messagingSenderId: '961049919020',
    projectId: 'wasteexpert-64848',
    storageBucket: 'wasteexpert-64848.appspot.com',
    iosBundleId: 'com.example.wasteexpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYWEroHjEi2K9YLct7aSRit4ED36C8O9s',
    appId: '1:961049919020:ios:ff1ebb4b61331fd14fdb89',
    messagingSenderId: '961049919020',
    projectId: 'wasteexpert-64848',
    storageBucket: 'wasteexpert-64848.appspot.com',
    iosBundleId: 'com.example.wasteexpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8T6W099hSsFf-WTiQC6-rW4VzklR6qNg',
    appId: '1:961049919020:web:f05ca56b7398676c4fdb89',
    messagingSenderId: '961049919020',
    projectId: 'wasteexpert-64848',
    authDomain: 'wasteexpert-64848.firebaseapp.com',
    storageBucket: 'wasteexpert-64848.appspot.com',
    measurementId: 'G-HGWTQ79YLS',
  );
}
